/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: swig.i

package cfdgo

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo CFLAGS: -I./external/cfd/include -I../cfd/include
#cgo LDFLAGS: -L/usr/local/lib -L${SRCDIR}/build/Release -L${SRCDIR}/build/Debug -lcfd

typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
extern void _wrap_Swig_free_cfdgo_0d8b6786211aa15d(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_cfdgo_0d8b6786211aa15d(swig_intgo arg1);
extern swig_intgo _wrap_kCfdSuccess_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdUnknownError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdInternalError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdMemoryFullError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdIllegalArgumentError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdIllegalStateError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdOutOfRangeError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdInvalidSettingError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdConnectionError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDiskAccessError_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdEnableBitcoin_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdEnableElements_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_CfdGetSupportedFunction_cfdgo_0d8b6786211aa15d(uintptr_t arg1);
extern swig_intgo _wrap_CfdInitialize_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_CfdFinalize_cfdgo_0d8b6786211aa15d(_Bool arg1);
extern swig_intgo _wrap_CfdCreateHandle_cfdgo_0d8b6786211aa15d(swig_voidp arg1);
extern swig_intgo _wrap_CfdFreeHandle_cfdgo_0d8b6786211aa15d(uintptr_t arg1);
extern swig_intgo _wrap_CfdFreeBuffer_cfdgo_0d8b6786211aa15d(uintptr_t arg1);
extern swig_intgo _wrap_CfdGetLastErrorCode_cfdgo_0d8b6786211aa15d(uintptr_t arg1);
extern swig_intgo _wrap_CfdGetLastErrorMessage_cfdgo_0d8b6786211aa15d(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_kCfdNetworkMainnet_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdNetworkTestnet_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdNetworkRegtest_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdNetworkLiquidv1_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdNetworkElementsRegtest_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdNetworkCustomChain_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2shAddress_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2pkhAddress_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2wshAddress_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2wpkhAddress_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2shP2wshAddress_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2shP2wpkhAddress_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2sh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2pkh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2wsh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2wpkh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2shP2wsh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdP2shP2wpkh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdSigHashAll_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdSigHashNone_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdSigHashSingle_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptNull_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptSh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptWsh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptPk_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptPkh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptWpkh_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptCombo_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptMulti_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptSortedMulti_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptAddr_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorScriptRaw_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorKeyNull_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorKeyPublic_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorKeyBip32_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_kCfdDescriptorKeyBip32Priv_cfdgo_0d8b6786211aa15d(void);
extern swig_intgo _wrap_CfdCreateAddress_cfdgo_0d8b6786211aa15d(uintptr_t arg1, swig_intgo arg2, swig_type_1 arg3, swig_type_2 arg4, swig_intgo arg5, swig_voidp arg6, swig_voidp arg7, swig_voidp arg8);
extern swig_intgo _wrap_CfdInitializeMultisigScript_cfdgo_0d8b6786211aa15d(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3, swig_voidp arg4);
extern swig_intgo _wrap_CfdAddMultisigScriptData_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2, swig_type_3 arg3);
extern swig_intgo _wrap_CfdFinalizeMultisigScript_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6);
extern swig_intgo _wrap_CfdFreeMultisigScriptHandle_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_CfdParseDescriptor_cfdgo_0d8b6786211aa15d(uintptr_t arg1, swig_type_4 arg2, swig_intgo arg3, swig_type_5 arg4, swig_voidp arg5, uintptr_t arg6);
extern swig_intgo _wrap_CfdGetDescriptorData_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5, swig_voidp arg6, swig_voidp arg7, swig_voidp arg8, swig_voidp arg9, swig_voidp arg10, swig_voidp arg11, swig_voidp arg12, swig_voidp arg13, swig_voidp arg14, swig_voidp arg15, uintptr_t arg16);
extern swig_intgo _wrap_CfdGetDescriptorMultisigKey_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7);
extern swig_intgo _wrap_CfdFreeDescriptorHandle_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_CfdGetAddressesFromMultisig_cfdgo_0d8b6786211aa15d(uintptr_t arg1, swig_type_6 arg2, swig_intgo arg3, swig_intgo arg4, swig_voidp arg5, uintptr_t arg6);
extern swig_intgo _wrap_CfdGetAddressFromMultisigKey_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_voidp arg4, swig_voidp arg5);
extern swig_intgo _wrap_CfdFreeAddressesMultisigHandle_cfdgo_0d8b6786211aa15d(uintptr_t arg1, uintptr_t arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_cfdgo_0d8b6786211aa15d(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Enum_SS_CfdErrorCode int
func _swig_getkCfdSuccess() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdSuccess_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdSuccess Enum_SS_CfdErrorCode = _swig_getkCfdSuccess()
func _swig_getkCfdUnknownError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdUnknownError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdUnknownError Enum_SS_CfdErrorCode = _swig_getkCfdUnknownError()
func _swig_getkCfdInternalError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdInternalError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdInternalError Enum_SS_CfdErrorCode = _swig_getkCfdInternalError()
func _swig_getkCfdMemoryFullError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdMemoryFullError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdMemoryFullError Enum_SS_CfdErrorCode = _swig_getkCfdMemoryFullError()
func _swig_getkCfdIllegalArgumentError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdIllegalArgumentError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdIllegalArgumentError Enum_SS_CfdErrorCode = _swig_getkCfdIllegalArgumentError()
func _swig_getkCfdIllegalStateError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdIllegalStateError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdIllegalStateError Enum_SS_CfdErrorCode = _swig_getkCfdIllegalStateError()
func _swig_getkCfdOutOfRangeError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdOutOfRangeError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdOutOfRangeError Enum_SS_CfdErrorCode = _swig_getkCfdOutOfRangeError()
func _swig_getkCfdInvalidSettingError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdInvalidSettingError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdInvalidSettingError Enum_SS_CfdErrorCode = _swig_getkCfdInvalidSettingError()
func _swig_getkCfdConnectionError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdConnectionError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdConnectionError Enum_SS_CfdErrorCode = _swig_getkCfdConnectionError()
func _swig_getkCfdDiskAccessError() (_swig_ret Enum_SS_CfdErrorCode) {
	var swig_r Enum_SS_CfdErrorCode
	swig_r = (Enum_SS_CfdErrorCode)(C._wrap_kCfdDiskAccessError_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDiskAccessError Enum_SS_CfdErrorCode = _swig_getkCfdDiskAccessError()
type Enum_SS_CfdLibraryFunction int
func _swig_getkCfdEnableBitcoin() (_swig_ret Enum_SS_CfdLibraryFunction) {
	var swig_r Enum_SS_CfdLibraryFunction
	swig_r = (Enum_SS_CfdLibraryFunction)(C._wrap_kCfdEnableBitcoin_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdEnableBitcoin Enum_SS_CfdLibraryFunction = _swig_getkCfdEnableBitcoin()
func _swig_getkCfdEnableElements() (_swig_ret Enum_SS_CfdLibraryFunction) {
	var swig_r Enum_SS_CfdLibraryFunction
	swig_r = (Enum_SS_CfdLibraryFunction)(C._wrap_kCfdEnableElements_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdEnableElements Enum_SS_CfdLibraryFunction = _swig_getkCfdEnableElements()
func CfdGetSupportedFunction(arg1 Uint64_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_CfdGetSupportedFunction_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func CfdInitialize() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CfdInitialize_cfdgo_0d8b6786211aa15d())
	return swig_r
}

func CfdFinalize(arg1 bool) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_CfdFinalize_cfdgo_0d8b6786211aa15d(C._Bool(_swig_i_0)))
	return swig_r
}

func CfdCreateHandle(arg1 *uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_CfdCreateHandle_cfdgo_0d8b6786211aa15d(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func CfdFreeHandle(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_CfdFreeHandle_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func CfdFreeBuffer(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_CfdFreeBuffer_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func CfdGetLastErrorCode(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_CfdGetLastErrorCode_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func CfdGetLastErrorMessage(arg1 uintptr, arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_CfdGetLastErrorMessage_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

type Enum_SS_CfdNetworkType int
func _swig_getkCfdNetworkMainnet() (_swig_ret Enum_SS_CfdNetworkType) {
	var swig_r Enum_SS_CfdNetworkType
	swig_r = (Enum_SS_CfdNetworkType)(C._wrap_kCfdNetworkMainnet_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdNetworkMainnet Enum_SS_CfdNetworkType = _swig_getkCfdNetworkMainnet()
func _swig_getkCfdNetworkTestnet() (_swig_ret Enum_SS_CfdNetworkType) {
	var swig_r Enum_SS_CfdNetworkType
	swig_r = (Enum_SS_CfdNetworkType)(C._wrap_kCfdNetworkTestnet_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdNetworkTestnet Enum_SS_CfdNetworkType = _swig_getkCfdNetworkTestnet()
func _swig_getkCfdNetworkRegtest() (_swig_ret Enum_SS_CfdNetworkType) {
	var swig_r Enum_SS_CfdNetworkType
	swig_r = (Enum_SS_CfdNetworkType)(C._wrap_kCfdNetworkRegtest_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdNetworkRegtest Enum_SS_CfdNetworkType = _swig_getkCfdNetworkRegtest()
func _swig_getkCfdNetworkLiquidv1() (_swig_ret Enum_SS_CfdNetworkType) {
	var swig_r Enum_SS_CfdNetworkType
	swig_r = (Enum_SS_CfdNetworkType)(C._wrap_kCfdNetworkLiquidv1_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdNetworkLiquidv1 Enum_SS_CfdNetworkType = _swig_getkCfdNetworkLiquidv1()
func _swig_getkCfdNetworkElementsRegtest() (_swig_ret Enum_SS_CfdNetworkType) {
	var swig_r Enum_SS_CfdNetworkType
	swig_r = (Enum_SS_CfdNetworkType)(C._wrap_kCfdNetworkElementsRegtest_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdNetworkElementsRegtest Enum_SS_CfdNetworkType = _swig_getkCfdNetworkElementsRegtest()
func _swig_getkCfdNetworkCustomChain() (_swig_ret Enum_SS_CfdNetworkType) {
	var swig_r Enum_SS_CfdNetworkType
	swig_r = (Enum_SS_CfdNetworkType)(C._wrap_kCfdNetworkCustomChain_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdNetworkCustomChain Enum_SS_CfdNetworkType = _swig_getkCfdNetworkCustomChain()
type Enum_SS_CfdAddressType int
func _swig_getkCfdP2shAddress() (_swig_ret Enum_SS_CfdAddressType) {
	var swig_r Enum_SS_CfdAddressType
	swig_r = (Enum_SS_CfdAddressType)(C._wrap_kCfdP2shAddress_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2shAddress Enum_SS_CfdAddressType = _swig_getkCfdP2shAddress()
func _swig_getkCfdP2pkhAddress() (_swig_ret Enum_SS_CfdAddressType) {
	var swig_r Enum_SS_CfdAddressType
	swig_r = (Enum_SS_CfdAddressType)(C._wrap_kCfdP2pkhAddress_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2pkhAddress Enum_SS_CfdAddressType = _swig_getkCfdP2pkhAddress()
func _swig_getkCfdP2wshAddress() (_swig_ret Enum_SS_CfdAddressType) {
	var swig_r Enum_SS_CfdAddressType
	swig_r = (Enum_SS_CfdAddressType)(C._wrap_kCfdP2wshAddress_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2wshAddress Enum_SS_CfdAddressType = _swig_getkCfdP2wshAddress()
func _swig_getkCfdP2wpkhAddress() (_swig_ret Enum_SS_CfdAddressType) {
	var swig_r Enum_SS_CfdAddressType
	swig_r = (Enum_SS_CfdAddressType)(C._wrap_kCfdP2wpkhAddress_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2wpkhAddress Enum_SS_CfdAddressType = _swig_getkCfdP2wpkhAddress()
func _swig_getkCfdP2shP2wshAddress() (_swig_ret Enum_SS_CfdAddressType) {
	var swig_r Enum_SS_CfdAddressType
	swig_r = (Enum_SS_CfdAddressType)(C._wrap_kCfdP2shP2wshAddress_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2shP2wshAddress Enum_SS_CfdAddressType = _swig_getkCfdP2shP2wshAddress()
func _swig_getkCfdP2shP2wpkhAddress() (_swig_ret Enum_SS_CfdAddressType) {
	var swig_r Enum_SS_CfdAddressType
	swig_r = (Enum_SS_CfdAddressType)(C._wrap_kCfdP2shP2wpkhAddress_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2shP2wpkhAddress Enum_SS_CfdAddressType = _swig_getkCfdP2shP2wpkhAddress()
type Enum_SS_CfdHashType int
func _swig_getkCfdP2sh() (_swig_ret Enum_SS_CfdHashType) {
	var swig_r Enum_SS_CfdHashType
	swig_r = (Enum_SS_CfdHashType)(C._wrap_kCfdP2sh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2sh Enum_SS_CfdHashType = _swig_getkCfdP2sh()
func _swig_getkCfdP2pkh() (_swig_ret Enum_SS_CfdHashType) {
	var swig_r Enum_SS_CfdHashType
	swig_r = (Enum_SS_CfdHashType)(C._wrap_kCfdP2pkh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2pkh Enum_SS_CfdHashType = _swig_getkCfdP2pkh()
func _swig_getkCfdP2wsh() (_swig_ret Enum_SS_CfdHashType) {
	var swig_r Enum_SS_CfdHashType
	swig_r = (Enum_SS_CfdHashType)(C._wrap_kCfdP2wsh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2wsh Enum_SS_CfdHashType = _swig_getkCfdP2wsh()
func _swig_getkCfdP2wpkh() (_swig_ret Enum_SS_CfdHashType) {
	var swig_r Enum_SS_CfdHashType
	swig_r = (Enum_SS_CfdHashType)(C._wrap_kCfdP2wpkh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2wpkh Enum_SS_CfdHashType = _swig_getkCfdP2wpkh()
func _swig_getkCfdP2shP2wsh() (_swig_ret Enum_SS_CfdHashType) {
	var swig_r Enum_SS_CfdHashType
	swig_r = (Enum_SS_CfdHashType)(C._wrap_kCfdP2shP2wsh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2shP2wsh Enum_SS_CfdHashType = _swig_getkCfdP2shP2wsh()
func _swig_getkCfdP2shP2wpkh() (_swig_ret Enum_SS_CfdHashType) {
	var swig_r Enum_SS_CfdHashType
	swig_r = (Enum_SS_CfdHashType)(C._wrap_kCfdP2shP2wpkh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdP2shP2wpkh Enum_SS_CfdHashType = _swig_getkCfdP2shP2wpkh()
type Enum_SS_CfdSighashType int
func _swig_getkCfdSigHashAll() (_swig_ret Enum_SS_CfdSighashType) {
	var swig_r Enum_SS_CfdSighashType
	swig_r = (Enum_SS_CfdSighashType)(C._wrap_kCfdSigHashAll_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdSigHashAll Enum_SS_CfdSighashType = _swig_getkCfdSigHashAll()
func _swig_getkCfdSigHashNone() (_swig_ret Enum_SS_CfdSighashType) {
	var swig_r Enum_SS_CfdSighashType
	swig_r = (Enum_SS_CfdSighashType)(C._wrap_kCfdSigHashNone_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdSigHashNone Enum_SS_CfdSighashType = _swig_getkCfdSigHashNone()
func _swig_getkCfdSigHashSingle() (_swig_ret Enum_SS_CfdSighashType) {
	var swig_r Enum_SS_CfdSighashType
	swig_r = (Enum_SS_CfdSighashType)(C._wrap_kCfdSigHashSingle_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdSigHashSingle Enum_SS_CfdSighashType = _swig_getkCfdSigHashSingle()
type Enum_SS_CfdDescriptorScriptType int
func _swig_getkCfdDescriptorScriptNull() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptNull_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptNull Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptNull()
func _swig_getkCfdDescriptorScriptSh() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptSh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptSh Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptSh()
func _swig_getkCfdDescriptorScriptWsh() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptWsh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptWsh Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptWsh()
func _swig_getkCfdDescriptorScriptPk() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptPk_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptPk Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptPk()
func _swig_getkCfdDescriptorScriptPkh() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptPkh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptPkh Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptPkh()
func _swig_getkCfdDescriptorScriptWpkh() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptWpkh_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptWpkh Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptWpkh()
func _swig_getkCfdDescriptorScriptCombo() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptCombo_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptCombo Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptCombo()
func _swig_getkCfdDescriptorScriptMulti() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptMulti_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptMulti Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptMulti()
func _swig_getkCfdDescriptorScriptSortedMulti() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptSortedMulti_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptSortedMulti Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptSortedMulti()
func _swig_getkCfdDescriptorScriptAddr() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptAddr_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptAddr Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptAddr()
func _swig_getkCfdDescriptorScriptRaw() (_swig_ret Enum_SS_CfdDescriptorScriptType) {
	var swig_r Enum_SS_CfdDescriptorScriptType
	swig_r = (Enum_SS_CfdDescriptorScriptType)(C._wrap_kCfdDescriptorScriptRaw_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorScriptRaw Enum_SS_CfdDescriptorScriptType = _swig_getkCfdDescriptorScriptRaw()
type Enum_SS_CfdDescriptorKeyType int
func _swig_getkCfdDescriptorKeyNull() (_swig_ret Enum_SS_CfdDescriptorKeyType) {
	var swig_r Enum_SS_CfdDescriptorKeyType
	swig_r = (Enum_SS_CfdDescriptorKeyType)(C._wrap_kCfdDescriptorKeyNull_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorKeyNull Enum_SS_CfdDescriptorKeyType = _swig_getkCfdDescriptorKeyNull()
func _swig_getkCfdDescriptorKeyPublic() (_swig_ret Enum_SS_CfdDescriptorKeyType) {
	var swig_r Enum_SS_CfdDescriptorKeyType
	swig_r = (Enum_SS_CfdDescriptorKeyType)(C._wrap_kCfdDescriptorKeyPublic_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorKeyPublic Enum_SS_CfdDescriptorKeyType = _swig_getkCfdDescriptorKeyPublic()
func _swig_getkCfdDescriptorKeyBip32() (_swig_ret Enum_SS_CfdDescriptorKeyType) {
	var swig_r Enum_SS_CfdDescriptorKeyType
	swig_r = (Enum_SS_CfdDescriptorKeyType)(C._wrap_kCfdDescriptorKeyBip32_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorKeyBip32 Enum_SS_CfdDescriptorKeyType = _swig_getkCfdDescriptorKeyBip32()
func _swig_getkCfdDescriptorKeyBip32Priv() (_swig_ret Enum_SS_CfdDescriptorKeyType) {
	var swig_r Enum_SS_CfdDescriptorKeyType
	swig_r = (Enum_SS_CfdDescriptorKeyType)(C._wrap_kCfdDescriptorKeyBip32Priv_cfdgo_0d8b6786211aa15d())
	return swig_r
}

var KCfdDescriptorKeyBip32Priv Enum_SS_CfdDescriptorKeyType = _swig_getkCfdDescriptorKeyBip32Priv()
func CfdCreateAddress(arg1 uintptr, arg2 int, arg3 string, arg4 string, arg5 int, arg6 *string, arg7 *string, arg8 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (int)(C._wrap_CfdCreateAddress_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_3)), C.swig_intgo(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func CfdInitializeMultisigScript(arg1 uintptr, arg2 int, arg3 int, arg4 *uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_CfdInitializeMultisigScript_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CfdAddMultisigScriptData(arg1 uintptr, arg2 uintptr, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_CfdAddMultisigScriptData_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func CfdFinalizeMultisigScript(arg1 uintptr, arg2 uintptr, arg3 Uint32_t, arg4 *string, arg5 *string, arg6 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_CfdFinalizeMultisigScript_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5)))
	return swig_r
}

func CfdFreeMultisigScriptHandle(arg1 uintptr, arg2 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_CfdFreeMultisigScriptHandle_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func CfdParseDescriptor(arg1 uintptr, arg2 string, arg3 int, arg4 string, arg5 *uintptr, arg6 Uint32_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	swig_r = (int)(C._wrap_CfdParseDescriptor_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_3)), C.swig_voidp(_swig_i_4), C.uintptr_t(_swig_i_5)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func CfdGetDescriptorData(arg1 uintptr, arg2 uintptr, arg3 Uint32_t, arg4 Uint32_t, arg5 Uint32_t, arg6 *int, arg7 *string, arg8 *string, arg9 *int, arg10 *string, arg11 *int, arg12 *string, arg13 *string, arg14 *string, arg15 *bool, arg16 Uint32_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	_swig_i_12 := arg13
	_swig_i_13 := arg14
	_swig_i_14 := arg15
	_swig_i_15 := arg16.Swigcptr()
	swig_r = (int)(C._wrap_CfdGetDescriptorData_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7), C.swig_voidp(_swig_i_8), C.swig_voidp(_swig_i_9), C.swig_voidp(_swig_i_10), C.swig_voidp(_swig_i_11), C.swig_voidp(_swig_i_12), C.swig_voidp(_swig_i_13), C.swig_voidp(_swig_i_14), C.uintptr_t(_swig_i_15)))
	return swig_r
}

func CfdGetDescriptorMultisigKey(arg1 uintptr, arg2 uintptr, arg3 Uint32_t, arg4 *int, arg5 *string, arg6 *string, arg7 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_CfdGetDescriptorMultisigKey_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6)))
	return swig_r
}

func CfdFreeDescriptorHandle(arg1 uintptr, arg2 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_CfdFreeDescriptorHandle_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func CfdGetAddressesFromMultisig(arg1 uintptr, arg2 string, arg3 int, arg4 int, arg5 *uintptr, arg6 Uint32_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	swig_r = (int)(C._wrap_CfdGetAddressesFromMultisig_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.swig_voidp(_swig_i_4), C.uintptr_t(_swig_i_5)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func CfdGetAddressFromMultisigKey(arg1 uintptr, arg2 uintptr, arg3 Uint32_t, arg4 *string, arg5 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_CfdGetAddressFromMultisigKey_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4)))
	return swig_r
}

func CfdFreeAddressesMultisigHandle(arg1 uintptr, arg2 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_CfdFreeAddressesMultisigHandle_cfdgo_0d8b6786211aa15d(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}


/**
 * Get supported function.
 * return: funcFlag    function flag.
 * return: _swig_ret   error code
 */
func CfdGoGetSupportedFunction() (funcFlag uint64, _swig_ret int) {
	funcFlagValue := SwigcptrUint64_t(uintptr(unsafe.Pointer(&funcFlag)))
	ret := CfdGetSupportedFunction(funcFlagValue)
	return funcFlag, ret
}

/**
 * Create cfd handle.
 * return: handle      cfd handle
 * return: _swig_ret   error code
 */
func CfdGoCreateHandle() (handle uintptr, _swig_ret int) {
	ret := CfdCreateHandle(&handle)
	return handle, ret
}

/**
 * Get last error message.
 * param: handle   cfd handle
 * return: message     last error message
 * return: _swig_ret   error code
 */
func CfdGoGetLastErrorMessage(handle uintptr) (message string, _swig_ret int) {
	ret := CfdGetLastErrorMessage(handle, &message)
	// Do not use the Free API as it will be released by Go-GC.
	return message, ret
}



/**
 * Create Address.
 * param: handle        cfd handle
 * param: hashType      hash type (p2pkh, p2sh, etc...)
 * param: pubkey        pubkey (pubkey hash only)
 * param: redeemScript  redeem script (script hash only)
 * param: networkType   network type
 * return: address                  address string
 * return: lockingScript            locking script
 * return: p2shSegwitLockingScript  p2sh-segwit witness program
 * return: _swig_ret                error code
 */
func CfdGoCreateAddress(handle uintptr, hashType int, pubkey string, redeemScript string, networkType int) (address string, lockingScript string, p2shSegwitLockingScript string, _swig_ret int) {
    ret := CfdCreateAddress(handle, hashType, pubkey, redeemScript, networkType, &address, &lockingScript, &p2shSegwitLockingScript)
    return address, lockingScript, p2shSegwitLockingScript, ret
}

/**
 * Create multisig script and address.
 * param: handle        cfd handle
 * param: networkType   network type
 * param: hashType      hash type (p2sh, p2wsh, etc...)
 * param: pubkeys       pubkey list (max 15 key)
 * param: requireNum    pubkey require signature
 * return: address        address string
 * return: redeemScript   redeem script
 * return: witnessScript  witness script
 * return: _swig_ret      error code
 */
func CfdGoCreateMultisigScript(handle uintptr, networkType int, hashType int, pubkeys []string, requireNum uint32) (address string, redeemScript string, witnessScript string, _swig_ret int) {
	var multisigHandle uintptr
	ret := CfdInitializeMultisigScript(handle, networkType, hashType, &multisigHandle)
	if ret == (int)(KCfdSuccess) {
		for i := 0; i < len(pubkeys); i++ {
			ret = CfdAddMultisigScriptData(handle, multisigHandle, pubkeys[i])
			if ret != (int)(KCfdSuccess) {
				break
			}
		}

		if ret == (int)(KCfdSuccess) {
			reqNumPtr := SwigcptrUint32_t(uintptr(unsafe.Pointer(&requireNum)))
			ret = CfdFinalizeMultisigScript(handle, multisigHandle, reqNumPtr, &address, &redeemScript, &witnessScript)
		}

		freeRet := CfdFreeMultisigScriptHandle(handle, multisigHandle)
		if ret == (int)(KCfdSuccess) {
			ret = freeRet
		}
	}
	return address, redeemScript, witnessScript, ret
}

/**
 * Descriptor data struct.
 */
type CfdDescriptorData struct {
	depth uint32
	scriptType int
	lockingScript string
	address string
	hashType int
	redeemScript string
	keyType int
	pubkey string
	extPubkey string
	extPrivkey string
	isMultisig bool
}

/**
 * Descriptor key data struct.
 */
type CfdDescriptorKeyData struct {
	keyType int
	pubkey string
	extPubkey string
	extPrivkey string
}

/**
 * Parse Output Descriptor.
 * param: handle               cfd handle
 * param: descriptor           output descriptor
 * param: networkType          network type
 * param: bip32DerivationPath  derive path
 * return: descriptorDataList  descriptor data struct list
 * return: multisigList        multisig key struct list
 * return: _swig_ret           error code
 */
func CfdGoParseDescriptor(handle uintptr, descriptor string, networkType int, bip32DerivationPath string) (descriptorDataList []CfdDescriptorData, multisigList []CfdDescriptorKeyData, _swig_ret int) {
	var descriptorHandle uintptr
	var maxIndex uint32
	maxIndexPtr := SwigcptrUint32_t(uintptr(unsafe.Pointer(&maxIndex)))
	ret := CfdParseDescriptor(handle, descriptor, networkType, bip32DerivationPath, &descriptorHandle, maxIndexPtr)
	if ret == (int)(KCfdSuccess) {
		var maxMultisigKeyNum uint32
		lastMultisigFlag := false
		keyNumPtr := SwigcptrUint32_t(uintptr(unsafe.Pointer(&maxMultisigKeyNum)))
		for i := uint32(0); i <= maxIndex; i++ {
			var data CfdDescriptorData
			var maxNum uint32
			maxNumPtr := SwigcptrUint32_t(uintptr(unsafe.Pointer(&maxNum)))
			depthPtr := SwigcptrUint32_t(uintptr(unsafe.Pointer(&(data.depth))))
			index := SwigcptrUint32_t(uintptr(unsafe.Pointer(&i)))
			ret = CfdGetDescriptorData(handle, descriptorHandle, index, maxNumPtr,
					depthPtr, &data.scriptType, &data.lockingScript,
					&data.address, &data.hashType, &data.redeemScript,
					&data.keyType, &data.pubkey, &data.extPubkey, &data.extPrivkey,
					&data.isMultisig, keyNumPtr)
			if ret != (int)(KCfdSuccess) {
				break
			}
			descriptorDataList = append(descriptorDataList, data)
			lastMultisigFlag = data.isMultisig
		}

		if lastMultisigFlag && (ret == (int)(KCfdSuccess)) {
			for i := uint32(0); i < maxMultisigKeyNum; i++ {
				var keyData CfdDescriptorKeyData
				index := SwigcptrUint32_t(uintptr(unsafe.Pointer(&i)))
				ret = CfdGetDescriptorMultisigKey(handle, descriptorHandle,
						index, &keyData.keyType, &keyData.pubkey,
						&keyData.extPubkey, &keyData.extPrivkey)
				if ret != (int)(KCfdSuccess) {
					break
				}
				multisigList = append(multisigList, keyData)
			}
		}

		freeRet := CfdFreeDescriptorHandle(handle, descriptorHandle)
		if ret == (int)(KCfdSuccess) {
			ret = freeRet
		}
	}
	return descriptorDataList, multisigList, ret
}

/**
 * Get multisig pubkeys address.
 * param: handle        cfd handle
 * param: redeemScript  multisig script
 * param: networkType   network type
 * param: hashType      hash type (p2sh, p2wsh, etc...)
 * return: addressList  address list
 * return: pubkeyList   pubkey list
 * return: _swig_ret    error code
 */
func CfdGoGetAddressesFromMultisig(handle uintptr, redeemScript string, networkType int, hashType int) (addressList []string, pubkeyList []string, _swig_ret int) {
	var multisigHandle uintptr
	var maxKeyNum uint32
	maxKeyNumPtr := SwigcptrUint32_t(uintptr(unsafe.Pointer(&maxKeyNum)))

	ret := CfdGetAddressesFromMultisig(handle, redeemScript, networkType,
			hashType, &multisigHandle, maxKeyNumPtr)
	if ret == (int)(KCfdSuccess) {
		for i := uint32(0); i < maxKeyNum; i++ {
			var pubkey string
			var address string
			index := SwigcptrUint32_t(uintptr(unsafe.Pointer(&i)))
			ret = CfdGetAddressFromMultisigKey(handle, multisigHandle,
					index, &address, &pubkey)
			if ret != (int)(KCfdSuccess) {
				break
			}
			addressList = append(addressList, address)
			pubkeyList = append(pubkeyList, pubkey)
		}

		freeRet := CfdFreeAddressesMultisigHandle(handle, multisigHandle)
		if ret == (int)(KCfdSuccess) {
			ret = freeRet
		}
	}
	return addressList, pubkeyList, ret
}



type SwigcptrUint64_t uintptr
type Uint64_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint64_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint32_t uintptr
type Uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

